server:
  port: 8002
spring:
  application:
    name: web-friends
  datasource:
    username: root
    password: 121122
    url: jdbc:mysql://localhost:3306/txbb
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka