server:
  port: 8000
spring:
  application:
    name: web-user
  datasource:
    username: root
    password: 121122
    url: jdbc:mysql://localhost:3306/txbb
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.111.128
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka
fdfs:
  serverip: http://192.168.111.128
  thumb-image:
    height: 80
    width: 80
  tracker-list:
    - 192.168.111.128:22122
  pool:
    jmx-enabled: false
logging:
  config: classpath:log4j2.xml